### PR TITLE
Added docker image

### PR DESCRIPTION
**Pull request by realSZ27**
There were *a lot* of commits that went into this, so I'll try to sum it up here.
1. Added a Dockerfile that builds the image from the new install-docker.sh file.
2. Added example docker-compose.yml
3. Updated README.md with new docker image and other info
4. Added .gitignore

## GitHub Workflow
~~The biggest thing that you have to do is get the new github workflow working with your accounts.
In the current one I included has a push to the ghcr, but since that isn't free for public repos,~~ Turns out it is, and its much easier than using docker hub. *In theory* you shouldn't have to do anything but make the variable and run it. If you have any issues with it (which I suspect you won't; github puts more restrictions on public forks), you can use [this comment](https://github.com/actions/runner/issues/1039#issuecomment-1019972535) as a source.

1. Make the only variable!
    - Make IMAGE_NAME whatever you like!
image
2. Make sure the example docker-compose.yml (the file **and** the one in the readme) image value matches whatever you made it (``ghcr.io/<your all lowercase username>/<IMAGE_NAME>:latest``). If it was successful, you should also see it in the packages section where you can click on it and see the image there.

### CODE REVIEW

**Comment by keepittechie** [comment]
Sorry, I've been busy at work. I didn't see you ready to merge. I'm also new to github. Let me know when you want to merge. I reviewed it.

**Comment by realSZ27** [comment]
No worries, I just found a couple of things that I wanted to change before I reopen.

**Comment by realSZ27** [comment]
Reopened and updated comment

**Comment by realSZ27** [comment]
@keepittechie It should be ready to merge now.

**Comment by keepittechie** [comment]
Sorry for the delay. I've been swamped at work.

**Pull request merged**
